export const ProjectActionTypes = {
  SET_LIST_DATA: 'project/SET_LIST_DATA',
  SET_DATA: 'project/SET_DATA',
  ON_PROCESS_SUBMIT: 'project/ON_PROCESS_SUBMIT',
  ON_FAILURE_SUBMIT: 'project/ON_FAILURE_SUBMIT',
  ON_SUCCESS_ADD: 'project/ON_SUCCESS_ADD',
  ON_SUCCESS_DELETE: 'project/ON_SUCCESS_DELETE',
  ON_SUCCESS_FETCH: 'project/ON_SUCCESS_FETCH',
  ON_SUCCESS_EDIT: 'project/ON_SUCCESS_EDIT',
  ON_FINISH_SUBMIT: 'project/ON_FINISH_SUBMIT',
};
